/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author gameV
 */
public class FrmCamara extends javax.swing.JFrame {

    /**
     * Creates new form FrmCamara
     */
    int largoCamara = 640;
    int anchoCamara = 480;
    private File imagenCapturada;
    private BufferedImage imagenBuffer;
    Dimension dimension = new Dimension(largoCamara, anchoCamara);
    Dimension dimension1 = WebcamResolution.VGA.getSize();
    Webcam webcam = Webcam.getDefault();
    WebcamPanel webcamPanel = new WebcamPanel(webcam, dimension, false);

    BufferedImage ruta;
    int contador = 0;

    public FrmCamara() {
        initComponents();
        setLocationRelativeTo(null);

        // Configuración inicial de la cámara
        webcam = Webcam.getDefault();
        if (webcam == null) {
            JOptionPane.showMessageDialog(this,
                    "No se encontró ninguna cámara disponible",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Configurar tamaño antes de abrir
        webcam.setViewSize(WebcamResolution.VGA.getSize());

        // Configurar el panel de la cámara
        webcamPanel = new WebcamPanel(webcam, new Dimension(640, 480), false);
        webcamPanel.setFillArea(true);
        webcamPanel.setFPSDisplayed(true);

        // Reemplazar el panel existente
        mostrarCamara.removeAll();
        mostrarCamara.setLayout(new BorderLayout());
        mostrarCamara.add(webcamPanel, BorderLayout.CENTER);
        mostrarCamara.revalidate();
        mostrarCamara.repaint();

        // Iniciar en estado apagado
        apagarBotones();

    }

    // Método para obtener la imagen capturada como File
    public File getImagenCapturada() {
        return imagenCapturada;
    }

    public void textoBotonesCuandoCargaCamara() {
        btnApagar.setText("Iniciando camara...");
        TomarFoto.setText("Iniciando camara...");
        btnGuardarFoto.setText("Iniciando camara...");
        btnPrender.setText("Iniciando camara...");
    }

    public void textoBotonesCuandoCargoCamara() {
        btnApagar.setText("APAGAR CAMARA");
        TomarFoto.setText("TOMAR FOTO");
        btnGuardarFoto.setText("SELECCIONAR FOTO");
        btnPrender.setText("INICIAR CAMARA");
    }

    public void prenderBotones() {
        btnApagar.setEnabled(true);
        TomarFoto.setEnabled(true);
    }

    public void apagarBotones() {
        btnApagar.setEnabled(false);
        TomarFoto.setEnabled(false);
        btnGuardarFoto.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mostrarCamara = new javax.swing.JPanel();
        TomarFoto = new javax.swing.JButton();
        btnPrender = new javax.swing.JButton();
        btnApagar = new javax.swing.JToggleButton();
        btnGuardarFoto = new javax.swing.JButton();
        txtFoto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblFotoTomada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mostrarCamara.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mostrarCamaraLayout = new javax.swing.GroupLayout(mostrarCamara);
        mostrarCamara.setLayout(mostrarCamaraLayout);
        mostrarCamaraLayout.setHorizontalGroup(
            mostrarCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mostrarCamaraLayout.setVerticalGroup(
            mostrarCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(mostrarCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 640, 360));

        TomarFoto.setText("Tomar foto");
        TomarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TomarFotoActionPerformed(evt);
            }
        });
        jPanel1.add(TomarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 200, 60));

        btnPrender.setText("INICIAR CAMARA");
        btnPrender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrender, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 150, 50));

        btnApagar.setText("APAGAR CAMARA");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 150, 50));

        btnGuardarFoto.setText("SELECCIONAR ESTA FOTO");
        btnGuardarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 240, 50));

        txtFoto.setForeground(new java.awt.Color(0, 0, 0));
        txtFoto.setText("Previsualización de la foto");
        jPanel1.add(txtFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lblFotoTomada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 180));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 270, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TomarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TomarFotoActionPerformed
        TomarFoto.setText("Tomar otra foto");
        btnGuardarFoto.setEnabled(true);

        ImageIcon foto;
        foto = new ImageIcon(webcam.getImage());
        Icon iconoFoto = new ImageIcon(foto.getImage().getScaledInstance(
                lblFotoTomada.getWidth(),
                lblFotoTomada.getHeight(),
                Image.SCALE_SMOOTH));
        lblFotoTomada.setIcon(iconoFoto);

        imagenBuffer = webcam.getImage();

    }//GEN-LAST:event_TomarFotoActionPerformed


    private void btnPrenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrenderActionPerformed
        textoBotonesCuandoCargaCamara();

        SwingUtilities.invokeLater(() -> {
            try {
                if (!webcam.isOpen()) {
                    webcam.open();
                }
                webcamPanel.start();
                prenderBotones();
                textoBotonesCuandoCargoCamara();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error al iniciar la cámara: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        btnPrender.setEnabled(false);
    }//GEN-LAST:event_btnPrenderActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        webcamPanel.stop();
        apagarBotones();
        btnPrender.setEnabled(true);

    }//GEN-LAST:event_btnApagarActionPerformed

    
    @Override
    public void dispose() {
        if (webcamPanel != null) {
            webcamPanel.stop();
        }
        if (webcam != null && webcam.isOpen()) {
            webcam.close();
        }
        super.dispose();
    }

    private void btnGuardarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFotoActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que quiere guardar esta fotografia?",
                "PREGUNTA", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (pregunta == 0) {
            try {

                imagenCapturada = File.createTempFile("enfermera_", ".jpg");
                ImageIO.write(imagenBuffer, "jpg", imagenCapturada);

                JOptionPane.showMessageDialog(this, "Foto capturada con éxito");
                this.dispose();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,
                        "Error al guardar la imagen: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnGuardarFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCamara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TomarFoto;
    private javax.swing.JToggleButton btnApagar;
    private javax.swing.JButton btnGuardarFoto;
    private javax.swing.JButton btnPrender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFotoTomada;
    private javax.swing.JPanel mostrarCamara;
    private javax.swing.JLabel txtFoto;
    // End of variables declaration//GEN-END:variables
}
