/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.UsuarioDAO;
import Model.Rol;
import Model.Usuario;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gameV
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        RolCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "DIRECTOR", "OFICIAL", "PERSONAL_DE_CONTROL", "OFICIAL_DE_REGISTRO", "ENFERMERA"
        }));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new RoundedPanel(30);
        tituloInpec = new javax.swing.JLabel();
        logoInpec = new javax.swing.JLabel();
        lema = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FieldUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        RolCmbBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/1117691499019247666-removebg-preview (3).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        jPanel6.setBackground(new java.awt.Color(29, 35, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloInpec.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        tituloInpec.setForeground(new java.awt.Color(255, 255, 255));
        tituloInpec.setText("INPEC");
        jPanel6.add(tituloInpec, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 160, -1));

        logoInpec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/inpec-removebg-preview (1).png"))); // NOI18N
        jPanel6.add(logoInpec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        lema.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lema.setForeground(new java.awt.Color(153, 153, 153));
        lema.setText("Con orden y precisión, aseguramos la institución.");
        jPanel6.add(lema, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correo:");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        FieldUsuario.setBackground(new java.awt.Color(29, 35, 51));
        FieldUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        FieldUsuario.setBorder(null);
        jPanel6.add(FieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 350, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-email-40.png"))); // NOI18N
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 40, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Diseño_sin_título__4_-removebg-preview (2).png"))); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        Password.setBackground(new java.awt.Color(29, 35, 51));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(null);
        jPanel6.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 350, 40));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 390, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 390, 10));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 170, 30));

        RolCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(RolCmbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 400, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 890, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String email = FieldUsuario.getText();
        String contraseña = new String(Password.getPassword());
        String rolTexto = (String) RolCmbBox.getSelectedItem();
        Rol rolSeleccionado = Rol.valueOf(rolTexto);

        UsuarioDAO usuarioDAO = new UsuarioDAO();
        Usuario usuario = usuarioDAO.validarCredenciales(email, contraseña, rolSeleccionado);

        if (usuario != null) {
            

            switch (usuario.getRol()) {
                case DIRECTOR:
                    new Director().setVisible(true);
                    break;
                case OFICIAL:
                    new Oficial().setVisible(true);
                    break;
                case PERSONAL_DE_CONTROL:
                    new PersonalDeControl().setVisible(true);
                    break;
                case OFICIAL_DE_REGISTRO:
                    new OficialRegistro().setVisible(true);
                    break;
                case ENFERMERA:
                    new Enfermera().setVisible(true);
                    break;
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Credenciales incorrectas o rol no coincide",
                    "Error de Login",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldUsuario;
    private javax.swing.JPasswordField Password;
    private javax.swing.JComboBox<String> RolCmbBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lema;
    private javax.swing.JLabel logoInpec;
    private javax.swing.JLabel tituloInpec;
    // End of variables declaration//GEN-END:variables
}
